version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - echo "Checking for dependencies"
      - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
  build:
    commands:
      - echo "Building SAM application"
      - sam build --use-container
      - sam package --s3-bucket ${DEPLOY_BUCKET} --output-template-file packaged.yaml
  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files:
    - packaged.yaml
  discard-paths: yes

cache:
  paths:
    - '/root/.cache/pip/**/*'