version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - echo "Checking for dependencies"
      - echo "Deploy bucket is: ${DEPLOY_BUCKET}"
      - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - echo "Deploy bucket is: ${DEPLOY_BUCKET}"

  build:
    commands:
      - aws s3 ls s3://${DEPLOY_BUCKET} || echo "Failed to access bucket"
      - echo "Building SAM application" 
      - sam build --use-container
      - sam package --s3-bucket ${DEPLOY_BUCKET} --output-template-file packaged.yaml
      - echo "Listing directory contents:"
      - ls -la
      - echo "Checking if packaged.yaml exists:"
      - test -f packaged.yaml && echo "packaged.yaml exists" || echo "packaged.yaml does not exist"
  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files:
    - packaged.yaml
  discard-paths: yes

cache:
  paths:
    - '/root/.cache/pip/**/*'


