AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  HitCounterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: WebsiteHitCounter/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        HttpGet:
          Type: Api
          Properties:
            Path: /
            Method: get

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hit-counter"