AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  HitCounterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: WebsiteHitCounter/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        HttpGet:
          Type: Api
          Properties:
            Path: /hit-counter
            Method: get
        HttpOptions:
          Type: Api
          Properties:
            Path: /hit-counter
            Method: options
      Policies:
        - AWSLambda_FullAccess
        - AmazonDynamoDBFullAccess

  HitCounterApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'GET,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hit-counter"